// Sedan Cars
import 'Car_Mode.dart';

List<Car> sedanCars = [
  Car(
    images: [
      'images/Sedan/Hyundai_i30/image1.png',
      'images/Sedan/Hyundai_i30/image2.png',
      'images/Sedan/Hyundai_i30/image3.png',
      'images/Sedan/Hyundai_i30/image4.png',
      'images/Sedan/Hyundai_i30/image5.png',
      'images/Sedan/Hyundai_i30/image6.png',
    ],
    name: 'Hyundai i30',
    description: 'The Hyundai i30 is a well-balanced premium sedan designed for everyday comfort and efficiency. It offers a smooth driving experience with responsive handling, modern interior ergonomics, and excellent ride quality. Ideal for city driving as well as long highway journeys, the i30 combines reliability with contemporary styling.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 2300000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 5,
    totalLength: 4585,
    overallWidth: 1795,
    overallHeight: 1475,
    wheelbase: 2650,
    groundClearance: 140,
    bootCapacity: 493,
    fuelTankCapacity: 50,
    brand: "Hyundai",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Sedan/Hyundai_Ioniq_6/image1.png',
      'images/Sedan/Hyundai_Ioniq_6/image2.png',
      'images/Sedan/Hyundai_Ioniq_6/image3.png',
      'images/Sedan/Hyundai_Ioniq_6/image4.png',
      'images/Sedan/Hyundai_Ioniq_6/image5.png',
      'images/Sedan/Hyundai_Ioniq_6/image6.png',
    ],
    name: 'Hyundai Ioniq 6',
    description: 'The Hyundai Ioniq 6 is a futuristic electric-inspired sedan focused on aerodynamics and efficiency. Its sleek silhouette, spacious cabin, and advanced technology make it a perfect choice for eco-conscious drivers seeking premium comfort and cutting-edge design.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 3600000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 5,
    totalLength: 4885,
    overallWidth: 1880,
    overallHeight: 1495,
    wheelbase: 2950,
    groundClearance: 141,
    bootCapacity: 401,
    fuelTankCapacity: 49,
    brand: "Hyundai",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Sedan/Nio_ET7/image1.png',
      'images/Sedan/Nio_ET7/image2.png',
      'images/Sedan/Nio_ET7/image3.png',
      'images/Sedan/Nio_ET7/image4.png',
      'images/Sedan/Nio_ET7/image5.png',
      'images/Sedan/Nio_ET7/image6.png',
    ],
    name: 'Nio ET7',
    description: 'The Nio ET7 is a flagship luxury sedan that delivers premium comfort, advanced autonomous driving features, and a high-end interior experience. Designed for executives and luxury enthusiasts, it provides effortless performance with an ultra-smooth ride and refined craftsmanship.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 5900000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 5,
    totalLength: 5101,
    overallWidth: 1987,
    overallHeight: 1509,
    wheelbase: 3060,
    groundClearance: 128,
    bootCapacity: 363,
    fuelTankCapacity: 50,
    brand: "Nio",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Sedan/Skoda_Octavia/image1.png',
      'images/Sedan/Skoda_Octavia/image2.png',
      'images/Sedan/Skoda_Octavia/image3.png',
      'images/Sedan/Skoda_Octavia/image4.png',
      'images/Sedan/Skoda_Octavia/image5.png',
      'images/Sedan/Skoda_Octavia/image6.png',
    ],
    name: 'Skoda Octavia',
    description: 'The Skoda Octavia is known for its exceptional cabin space, practicality, and solid build quality. With one of the largest boot capacities in its segment, it’s perfect for families and professionals who require comfort, performance, and practicality in one package.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 2800000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 5,
    totalLength: 4698,
    overallWidth: 1829,
    overallHeight: 1470,
    wheelbase: 2686,
    groundClearance: 143,
    bootCapacity: 600,
    fuelTankCapacity: 45,
    brand: "Skoda",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Sedan/Toyota_Camry/image1.png',
      'images/Sedan/Toyota_Camry/image2.png',
      'images/Sedan/Toyota_Camry/image3.png',
      'images/Sedan/Toyota_Camry/image4.png',
      'images/Sedan/Toyota_Camry/image5.png',
      'images/Sedan/Toyota_Camry/image6.png',
    ],
    name: 'Toyota Camry',
    description: 'The Toyota Camry is a globally trusted sedan offering unmatched reliability, smooth ride comfort, and premium interior refinement. Known for its long-term durability and low maintenance costs, it is a perfect sedan for executives and daily commuters alike.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 3500000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 4,
    totalLength: 4885,
    overallWidth: 1840,
    overallHeight: 1445,
    wheelbase: 2825,
    groundClearance: 140,
    bootCapacity: 524,
    fuelTankCapacity: 50,
    brand: "Toyota",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Sedan/Volvo_S90/image1.png',
      'images/Sedan/Volvo_S90/image2.png',
      'images/Sedan/Volvo_S90/image3.png',
      'images/Sedan/Volvo_S90/image4.png',
      'images/Sedan/Volvo_S90/image5.png',
      'images/Sedan/Volvo_S90/image6.png',
    ],
    name: 'Volvo S90',
    description: 'The Volvo S90 is a luxury Scandinavian sedan focused on safety, elegance, and advanced driver assistance technologies. With its minimalist interior design, superior comfort, and strong safety credentials, it delivers a calm and confident driving experience.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 6900000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 4,
    totalLength: 4969,
    overallWidth: 1879,
    overallHeight: 1440,
    wheelbase: 2941,
    groundClearance: 152,
    bootCapacity: 560,
    fuelTankCapacity: 60,
    brand: "Volvo",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Sedan/BMW_2_F44/image1.png',
      'images/Sedan/BMW_2_F44/image2.png',
      'images/Sedan/BMW_2_F44/image3.png',
      'images/Sedan/BMW_2_F44/image4.png',
      'images/Sedan/BMW_2_F44/image5.png',
      'images/Sedan/BMW_2_F44/image6.png',
    ],
    name: 'BMW 2 F44',
    description: 'The BMW 2 Series Gran Coupe delivers sporty dynamics wrapped in a compact luxury sedan form. Designed for enthusiastic drivers, it offers precise steering, aggressive styling, and a premium driving experience with BMW’s signature performance DNA.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 4500000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 4,
    totalLength: 4526,
    overallWidth: 1800,
    overallHeight: 1420,
    wheelbase: 2670,
    groundClearance: 152,
    bootCapacity: 430,
    fuelTankCapacity: 50,
    brand: "BMW",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Sedan/BMW_5_G60/image1.png',
      'images/Sedan/BMW_5_G60/image2.png',
      'images/Sedan/BMW_5_G60/image3.png',
      'images/Sedan/BMW_5_G60/image4.png',
      'images/Sedan/BMW_5_G60/image5.png',
      'images/Sedan/BMW_5_G60/image6.png',
    ],
    name: 'BMW 5 G60',
    description: 'The BMW 5 Series is a luxury executive sedan that blends performance, comfort, and cutting-edge technology. It offers a refined driving experience with powerful road presence, making it a benchmark in the premium sedan segment.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 7500000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 4,
    totalLength: 5060,
    overallWidth: 1900,
    overallHeight: 1515,
    wheelbase: 2995,
    groundClearance: 154,
    bootCapacity: 520,
    fuelTankCapacity: 60,
    brand: "BMW",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Sedan/BMW_7_G70/image1.png',
      'images/Sedan/BMW_7_G70/image2.png',
      'images/Sedan/BMW_7_G70/image3.png',
      'images/Sedan/BMW_7_G70/image4.png',
      'images/Sedan/BMW_7_G70/image5.png',
      'images/Sedan/BMW_7_G70/image6.png',
    ],
    name: 'BMW 7 G70',
    description: 'The BMW 7 Series represents ultimate luxury and innovation. Designed for comfort-focused buyers, it offers unmatched rear-seat luxury, advanced infotainment, premium materials, and effortless performance suitable for chauffeur-driven experiences.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 17500000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Sedan',
    numberOfDoors: 4,
    totalLength: 5391,
    overallWidth: 1950,
    overallHeight: 1544,
    wheelbase: 1194,
    groundClearance: 525,
    bootCapacity: 525,
    fuelTankCapacity: 60,
    brand: "BMW",
    fuelType: "Petrol",
  ),
];

// SUV Cars
List<Car> suvCars = [
 Car(
  images: [
    'images/SUV/Jaecoo_7/image1.png',
    'images/SUV/Jaecoo_7/image2.png',
    'images/SUV/Jaecoo_7/image3.png',
    'images/SUV/Jaecoo_7/image4.png',
    'images/SUV/Jaecoo_7/image5.png',
    'images/SUV/Jaecoo_7/image6.png',
  ],
  name: 'Jaecoo 7',
  description: 'The Jaecoo 7 is a modern SUV designed with rugged aesthetics and urban practicality. It offers a comfortable cabin, elevated driving position, and advanced safety features, making it suitable for both city roads and light off-road adventures.',
  transmission: 'Automatic',
  seats: 5,
  totalPrice: 3300000,
  topSpeed: 200,
  mileage: 12.5,
  horsepower: 150,
  bodyType: 'SUV',
  numberOfDoors: 5,
  totalLength: 4500,
  overallWidth: 1865,
  overallHeight: 1680,
  wheelbase: 2672,
  groundClearance: 200,
  bootCapacity: 480,
  fuelTankCapacity: 57,
   brand: "Jaecoo",
   fuelType: "Petrol",
 ),

  Car(
    images: [
      'images/SUV/Dacia_Duster/image1.png',
      'images/SUV/Dacia_Duster/image2.png',
      'images/SUV/Dacia_Duster/image3.png',
      'images/SUV/Dacia_Duster/image4.png',
      'images/SUV/Dacia_Duster/image5.png',
      'images/SUV/Dacia_Duster/image6.png',
    ],
    name: 'Dacia Duster',
    description: 'The Dacia Duster is a practical and budget-friendly SUV known for its strong ground clearance and durable build. It is ideal for customers looking for a no-nonsense SUV capable of handling rough roads without compromising comfort.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 1600000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'SUV',
    numberOfDoors: 5,
    totalLength: 4343,
    overallWidth: 1813,
    overallHeight: 1656,
    wheelbase: 2657,
    groundClearance: 209,
    bootCapacity: 430,
    fuelTankCapacity: 49,
    brand: "Dacia",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/SUV/Nissan_Qashqai/image1.png',
      'images/SUV/Nissan_Qashqai/image2.png',
      'images/SUV/Nissan_Qashqai/image3.png',
      'images/SUV/Nissan_Qashqai/image4.png',
      'images/SUV/Nissan_Qashqai/image5.png',
      'images/SUV/Nissan_Qashqai/image6.png',
    ],
    name: 'Nissan Qashqai',
    description: 'The Nissan Qashqai is a stylish and versatile compact SUV offering smooth ride quality, smart interior design, and advanced safety features. It is perfect for urban families looking for efficiency, comfort, and modern aesthetics.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 3200000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'SUV',
    numberOfDoors: 5,
    totalLength: 4425,
    overallWidth: 1835,
    overallHeight: 1625,
    wheelbase: 2665,
    groundClearance: 175,
    bootCapacity: 479,
    fuelTankCapacity: 55,
    brand: "Nissan",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/SUV/Renault_Rafale/image1.png',
      'images/SUV/Renault_Rafale/image2.png',
      'images/SUV/Renault_Rafale/image3.png',
      'images/SUV/Renault_Rafale/image4.png',
      'images/SUV/Renault_Rafale/image5.png',
      'images/SUV/Renault_Rafale/image6.png',
    ],
    name: 'Renault Rafale',
    description: 'The Renault Rafale is a premium coupe-style SUV that combines sporty design with advanced hybrid-friendly engineering. Its bold styling, spacious cabin, and smooth ride make it an attractive choice in the modern SUV segment.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 4800000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'SUV',
    numberOfDoors: 5,
    totalLength: 4710,
    overallWidth: 1866,
    overallHeight: 1613,
    wheelbase: 2738,
    groundClearance: 145,
    bootCapacity: 630,
    fuelTankCapacity: 55,
    brand: "Renault",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/SUV/Ford_Explorer/image1.png',
      'images/SUV/Ford_Explorer/image2.png',
      'images/SUV/Ford_Explorer/image3.png',
      'images/SUV/Ford_Explorer/image4.png',
      'images/SUV/Ford_Explorer/image5.png',
      'images/SUV/Ford_Explorer/image6.png',
    ],
    name: 'Ford Explorer',
    description: 'The Ford Explorer is a robust mid-size SUV designed for comfort, performance, and long-distance travel. With a spacious interior and strong road presence, it is ideal for families seeking a powerful and reliable SUV.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 5500000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'SUV',
    numberOfDoors: 5,
    totalLength: 4343,
    overallWidth: 1813,
    overallHeight: 1656,
    wheelbase: 2657,
    groundClearance: 209,
    bootCapacity: 430,
    fuelTankCapacity: 49,
    brand: "Ford",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/SUV/BMW_X5_G05/image1.png',
      'images/SUV/BMW_X5_G05/image2.png',
      'images/SUV/BMW_X5_G05/image3.png',
      'images/SUV/BMW_X5_G05/image4.png',
      'images/SUV/BMW_X5_G05/image5.png',
      'images/SUV/BMW_X5_G05/image6.png',
    ],
    name: 'BMW X5 G05',
    description: 'The BMW X5 is a luxury performance SUV that blends athletic handling with premium comfort. Known for its powerful road presence and refined interior, it offers excellent driving dynamics both on highways and rough terrain.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 10500000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'SUV',
    numberOfDoors: 5,
    totalLength: 4922,
    overallWidth: 2004,
    overallHeight: 1745,
    wheelbase: 2975,
    groundClearance: 214,
    bootCapacity: 650,
    fuelTankCapacity: 83,
    brand: "BMW",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/SUV/Mercedes_G_W463/image1.png',
      'images/SUV/Mercedes_G_W463/image2.png',
      'images/SUV/Mercedes_G_W463/image3.png',
      'images/SUV/Mercedes_G_W463/image4.png',
      'images/SUV/Mercedes_G_W463/image5.png',
      'images/SUV/Mercedes_G_W463/image6.png',
    ],
    name: 'Mercedes G W463',
    description: 'The Mercedes-Benz G-Class is an iconic luxury off-road SUV renowned for its rugged design and extreme capability. It combines luxury interiors with legendary off-road performance, making it a status symbol worldwide.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 30000000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'SUV',
    numberOfDoors: 5,
    totalLength: 4669,
    overallWidth: 1931,
    overallHeight: 1969,
    wheelbase: 2890,
    groundClearance: 214,
    bootCapacity: 667,
    fuelTankCapacity: 100,
    brand: "Mercedes",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/SUV/Mercedes_GLS_X167/image1.png',
      'images/SUV/Mercedes_GLS_X167/image2.png',
      'images/SUV/Mercedes_GLS_X167/image3.png',
      'images/SUV/Mercedes_GLS_X167/image4.png',
      'images/SUV/Mercedes_GLS_X167/image5.png',
      'images/SUV/Mercedes_GLS_X167/image6.png',
    ],
    name: 'Mercedes GLS X167',
    description: 'The Mercedes GLS is a full-size luxury SUV offering exceptional comfort, space, and advanced technology. With a refined cabin and smooth ride, it provides a first-class experience for all passengers.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 13000000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'SUV',
    numberOfDoors: 5,
    totalLength: 5208,
    overallWidth: 1956,
    overallHeight: 1838,
    wheelbase: 3135,
    groundClearance: 160,
    bootCapacity: 520,
    fuelTankCapacity: 90,
    brand: "Mercedes",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/SUV/Volkswagen_Touareg/image1.png',
      'images/SUV/Volkswagen_Touareg/image2.png',
      'images/SUV/Volkswagen_Touareg/image3.png',
      'images/SUV/Volkswagen_Touareg/image4.png',
      'images/SUV/Volkswagen_Touareg/image5.png',
      'images/SUV/Volkswagen_Touareg/image6.png',
    ],
    name: 'Volkswagen Touareg',
    description: 'The Volkswagen Touareg is a premium SUV known for its refined driving dynamics, solid build quality, and understated luxury. It delivers a comfortable ride while maintaining impressive off-road capabilities.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 7200000,
    topSpeed: 200,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'SUV',
    numberOfDoors: 5,
    totalLength: 4902,
    overallWidth: 1984,
    overallHeight: 1693,
    wheelbase: 2899,
    groundClearance: 209,
    bootCapacity: 665,
    fuelTankCapacity: 76,
    brand: "Volkswagen",
    fuelType: "Petrol",
  ),
];

// Sports Cars
List<Car> Coupe = [
  Car(
    images: [
      'images/Coupe/BMW_i8/image1.png',
      'images/Coupe/BMW_i8/image2.png',
      'images/Coupe/BMW_i8/image3.png',
      'images/Coupe/BMW_i8/image4.png',
      'images/Coupe/BMW_i8/image5.png',
      'images/Coupe/BMW_i8/image6.png',
    ],
    name: 'BMW i8',
    description: 'The BMW i8 is a futuristic sports coupe blending performance with hybrid technology. Its aggressive design, lightweight construction, and thrilling acceleration make it a standout supercar for eco-conscious performance enthusiasts.',
    transmission: 'Manual',
    seats: 4,
    totalPrice: 15000000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Coupe',
    numberOfDoors: 2,
    totalLength: 4689,
    overallWidth: 1942,
    overallHeight: 1293,
    wheelbase: 2800,
    groundClearance: 117,
    bootCapacity: 154,
    fuelTankCapacity: 30,
    brand: "BMW",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Coupe/Dodge_Challenger/image1.png',
      'images/Coupe/Dodge_Challenger/image2.png',
      'images/Coupe/Dodge_Challenger/image3.png',
      'images/Coupe/Dodge_Challenger/image4.png',
      'images/Coupe/Dodge_Challenger/image5.png',
      'images/Coupe/Dodge_Challenger/image6.png',
    ],
    name: 'Dodge Challenger',
    description: 'The Dodge Challenger is a classic American muscle car delivering brute power, bold styling, and aggressive road presence. It offers exhilarating performance and a commanding driving experience.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 8200000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 728,
    bodyType: 'Coupe',
    numberOfDoors: 2,
    totalLength: 5026,
    overallWidth: 1986,
    overallHeight: 1459,
    wheelbase: 2950,
    groundClearance: 130,
    bootCapacity: 460,
    fuelTankCapacity: 70,
    brand: "Dodge",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Coupe/Ford_Mustang/image1.png',
      'images/Coupe/Ford_Mustang/image2.png',
      'images/Coupe/Ford_Mustang/image3.png',
      'images/Coupe/Ford_Mustang/image4.png',
      'images/Coupe/Ford_Mustang/image5.png',
      'images/Coupe/Ford_Mustang/image6.png',
    ],
    name: 'Ford Mustang',
    description: 'The Ford Mustang is an iconic sports coupe symbolizing power and freedom. With its muscular design and strong performance, it delivers an exciting driving experience for true car enthusiasts.',
    transmission: 'Manual',
    seats: 4,
    totalPrice: 7500000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Coupe',
    numberOfDoors: 2,
    totalLength: 4810,
    overallWidth: 1916,
    overallHeight: 1404,
    wheelbase: 2719,
    groundClearance: 153,
    bootCapacity: 381,
    fuelTankCapacity: 61,
    brand: "Ford",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Coupe/McLaren_720S/image1.png',
      'images/Coupe/McLaren_720S/image2.png',
      'images/Coupe/McLaren_720S/image3.png',
      'images/Coupe/McLaren_720S/image4.png',
      'images/Coupe/McLaren_720S/image5.png',
      'images/Coupe/McLaren_720S/image6.png',
    ],
    name: 'McLaren 720S',
    description: 'The McLaren 720S is a high-performance supercar engineered for extreme speed and precision handling. With lightweight construction and aerodynamic perfection, it offers a race-inspired driving experience.',
    transmission: 'Manual',
    seats: 2,
    totalPrice: 52000000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Coupe',
    numberOfDoors: 2,
    totalLength: 4543,
    overallWidth: 1930,
    overallHeight: 1196,
    wheelbase: 2670,
    groundClearance: 130,
    bootCapacity: 360,
    fuelTankCapacity: 30,
    brand: "McLaren",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Coupe/Porsche_911/image1.png',
      'images/Coupe/Porsche_911/image2.png',
      'images/Coupe/Porsche_911/image3.png',
      'images/Coupe/Porsche_911/image4.png',
      'images/Coupe/Porsche_911/image5.png',
      'images/Coupe/Porsche_911/image6.png',
    ],
    name: 'Porsche 911',
    description: 'The Porsche 911 is a legendary sports car known for its timeless design, precision handling, and thrilling performance. It delivers an unmatched balance between everyday usability and track-level capability.',
    transmission: 'Manual',
    seats: 4,
    totalPrice: 20000000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Coupe',
    numberOfDoors: 2,
    totalLength: 4553,
    overallWidth: 1852,
    overallHeight: 1294,
    wheelbase: 2450,
    groundClearance: 130,
    bootCapacity: 135,
    fuelTankCapacity: 67,
    brand: "Porsche",
    fuelType: "Petrol",
  ),
];

// Hatchback Cars
List<Car> Hatchback = [
  Car(
    images: [
      'images/Hatchback/Cupra_Leon/image1.png',
      'images/Hatchback/Cupra_Leon/image2.png',
      'images/Hatchback/Cupra_Leon/image3.png',
      'images/Hatchback/Cupra_Leon/image4.png',
      'images/Hatchback/Cupra_Leon/image5.png',
      'images/Hatchback/Cupra_Leon/image6.png',
    ],
    name: 'Cupra Leon',
    description: 'The Cupra Leon is a sporty hatchback offering sharp handling, bold styling, and performance-oriented engineering. It delivers an exciting driving experience while maintaining everyday practicality.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 3500000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Hetchback',
    numberOfDoors: 5,
    totalLength: 4689,
    overallWidth: 1942,
    overallHeight: 1293,
    wheelbase: 2800,
    groundClearance: 117,
    bootCapacity: 154,
    fuelTankCapacity: 30,
    brand: "Cupra",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Hatchback/Dacia_Spring/image1.png',
      'images/Hatchback/Dacia_Spring/image2.png',
      'images/Hatchback/Dacia_Spring/image3.png',
      'images/Hatchback/Dacia_Spring/image4.png',
      'images/Hatchback/Dacia_Spring/image5.png',
      'images/Hatchback/Dacia_Spring/image6.png',
    ],
    name: 'Dacia Spring',
    description: 'The Dacia Spring is a compact city-friendly hatchback designed for efficiency and affordability. Its small size makes it perfect for urban commuting and tight parking spaces.',
    transmission: 'Manual',
    seats: 4,
    totalPrice: 1400000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Hetchback',
    numberOfDoors: 5,
    totalLength: 3701,
    overallWidth: 1583,
    overallHeight: 1519,
    wheelbase: 2423,
    groundClearance: 155,
    bootCapacity: 308,
    fuelTankCapacity: 50,
    brand: "Dacia",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Hatchback/Skoda_Scala/image1.png',
      'images/Hatchback/Skoda_Scala/image2.png',
      'images/Hatchback/Skoda_Scala/image3.png',
      'images/Hatchback/Skoda_Scala/image4.png',
      'images/Hatchback/Skoda_Scala/image5.png',
      'images/Hatchback/Skoda_Scala/image6.png',
    ],
    name: 'Skoda Scala',
    description: 'The Skoda Scala is a premium hatchback offering generous interior space, modern technology, and refined ride quality. It’s ideal for families and city drivers alike.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 2200000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Hetchback',
    numberOfDoors: 5,
    totalLength: 4365,
    overallWidth: 1793,
    overallHeight: 1471,
    wheelbase: 2649,
    groundClearance: 149,
    bootCapacity: 467,
    fuelTankCapacity: 50,
    brand: "Skoda",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Hatchback/Suzuki_Swift/image1.png',
      'images/Hatchback/Suzuki_Swift/image2.png',
      'images/Hatchback/Suzuki_Swift/image3.png',
      'images/Hatchback/Suzuki_Swift/image4.png',
      'images/Hatchback/Suzuki_Swift/image5.png',
      'images/Hatchback/Suzuki_Swift/image6.png',
    ],
    name: 'Suzuki Swift',
    description: 'The Suzuki Swift is a fun-to-drive compact hatchback known for its lightweight design, agile handling, and fuel efficiency. It’s perfect for urban drivers looking for reliability and ease of use.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 800000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Hetchback',
    numberOfDoors: 5,
    totalLength: 3860,
    overallWidth: 1735,
    overallHeight: 1495,
    wheelbase: 2450,
    groundClearance: 115,
    bootCapacity: 265,
    fuelTankCapacity: 37,
    brand: "Suzuki",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Hatchback/Volkswagen_Golf/image1.png',
      'images/Hatchback/Volkswagen_Golf/image2.png',
      'images/Hatchback/Volkswagen_Golf/image3.png',
      'images/Hatchback/Volkswagen_Golf/image4.png',
      'images/Hatchback/Volkswagen_Golf/image5.png',
      'images/Hatchback/Volkswagen_Golf/image6.png',
    ],
    name: 'Volkswagen Golf',
    description: 'The Volkswagen Golf is a benchmark hatchback offering a perfect balance of performance, comfort, and build quality. It remains one of the most refined and versatile hatchbacks globally.',
    transmission: 'Manual',
    seats: 5,
    totalPrice: 3700000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Hetchback',
    numberOfDoors: 5,
    totalLength: 4282,
    overallWidth: 1789,
    overallHeight: 1483,
    wheelbase: 2620,
    groundClearance: 137,
    bootCapacity: 381,
    fuelTankCapacity: 45,
    brand: "Volkswagen",
    fuelType: "Petrol",
  ),
];

// Offroad Cars
List<Car> Convertible = [
  Car(
    images: [
      'images/Convertible/BMW_4/image1.png',
      'images/Convertible/BMW_4/image2.png',
      'images/Convertible/BMW_4/image3.png',
      'images/Convertible/BMW_4/image4.png',
      'images/Convertible/BMW_4/image5.png',
      'images/Convertible/BMW_4/image6.png',
    ],
    name: 'BMW 4',
    description: 'The BMW 4 Series Convertible combines sporty performance with open-top luxury. It delivers refined handling, premium interiors, and an immersive driving experience under the open sky.',
    transmission: 'Manual',
    seats: 4,
    totalPrice: 9000000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Convertible',
    numberOfDoors: 2,
    totalLength: 4794,
    overallWidth: 1887,
    overallHeight: 1395,
    wheelbase: 2857,
    groundClearance: 126,
    bootCapacity: 385,
    fuelTankCapacity: 59,
    brand: "BMW",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Convertible/Ford_Mustang/image1.png',
      'images/Convertible/Ford_Mustang/image2.png',
      'images/Convertible/Ford_Mustang/image3.png',
      'images/Convertible/Ford_Mustang/image4.png',
      'images/Convertible/Ford_Mustang/image5.png',
      'images/Convertible/Ford_Mustang/image6.png',
    ],
    name: 'Ford Mustang',
    description: 'The Ford Mustang Convertible delivers classic American muscle performance with the freedom of open-top driving. It’s designed for those who seek performance with style and emotion.',
    transmission: 'Manual',
    seats: 4,
    totalPrice: 9000000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Convertible',
    numberOfDoors: 2,
    totalLength: 4784,
    overallWidth: 1916,
    overallHeight: 1394,
    wheelbase: 2720,
    groundClearance: 117,
    bootCapacity: 332,
    fuelTankCapacity: 61,
    brand: "Ford",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Convertible/Mazda_MX_5/image1.png',
      'images/Convertible/Mazda_MX_5/image2.png',
      'images/Convertible/Mazda_MX_5/image3.png',
      'images/Convertible/Mazda_MX_5/image4.png',
      'images/Convertible/Mazda_MX_5/image5.png',
      'images/Convertible/Mazda_MX_5/image6.png',
    ],
    name: 'Mazda MX 5',
    description: 'The Mazda MX-5 is a lightweight roadster built for pure driving pleasure. With perfect balance and responsive handling, it offers an engaging and fun-to-drive experience.',
    transmission: 'Manual',
    seats: 2,
    totalPrice: 4500000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Convertible',
    numberOfDoors: 2,
    totalLength: 3915,
    overallWidth: 1735,
    overallHeight: 1225,
    wheelbase: 2310,
    groundClearance: 125,
    bootCapacity: 130,
    fuelTankCapacity: 45,
    brand: "Mazda",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Convertible/Mercedes_SL/image1.png',
      'images/Convertible/Mercedes_SL/image2.png',
      'images/Convertible/Mercedes_SL/image3.png',
      'images/Convertible/Mercedes_SL/image4.png',
      'images/Convertible/Mercedes_SL/image5.png',
      'images/Convertible/Mercedes_SL/image6.png',
    ],
    name: 'Mercedes SL',
    description: 'The Mercedes SL is a luxury grand tourer convertible offering elegance, comfort, and performance. Designed for long-distance cruising, it combines open-air freedom with refined luxury.',
    transmission: 'Manual',
    seats: 4,
    totalPrice: 30000000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Convertible',
    numberOfDoors: 2,
    totalLength: 4700,
    overallWidth: 1915,
    overallHeight: 1359,
    wheelbase: 2700,
    groundClearance: 127,
    bootCapacity: 213,
    fuelTankCapacity: 70,
    brand: "Mercedes",
    fuelType: "Petrol",
  ),
  Car(
    images: [
      'images/Convertible/Porsche_718/image1.png',
      'images/Convertible/Porsche_718/image2.png',
      'images/Convertible/Porsche_718/image3.png',
      'images/Convertible/Porsche_718/image4.png',
      'images/Convertible/Porsche_718/image5.png',
      'images/Convertible/Porsche_718/image6.png',
    ],
    name: 'Porsche 718',
    description: 'The Porsche 718 is a precision-engineered convertible sports car delivering outstanding agility and performance. Its mid-engine layout ensures sharp handling and thrilling acceleration.',
    transmission: 'Manual',
    seats: 2,
    totalPrice: 15000000,
    topSpeed: 250,
    mileage: 12.5,
    horsepower: 150,
    bodyType: 'Convertible',
    numberOfDoors: 2,
    totalLength: 4391,
    overallWidth: 1801,
    overallHeight: 1262,
    wheelbase: 2475,
    groundClearance: 131,
    bootCapacity: 270,
    fuelTankCapacity: 64,
    brand: "Porsche",
    fuelType: "Petrol",
  ),
];
