// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7CmbfmAWTPDxqZEvOWWxpPjLM_U2fKw',
    appId: '1:575931384947:web:0e08324dc9e0db95615606',
    messagingSenderId: '575931384947',
    projectId: 'cardealer-187bf',
    authDomain: 'cardealer-187bf.firebaseapp.com',
    storageBucket: 'cardealer-187bf.firebasestorage.app',
    measurementId: 'G-RTNPCQCGT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYGF42sUkz9hUfPaS1hq5aYhSZ1VE63Q0',
    appId: '1:575931384947:android:1c8c58d197b021d6615606',
    messagingSenderId: '575931384947',
    projectId: 'cardealer-187bf',
    storageBucket: 'cardealer-187bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbDl50mkTiDjFskxj1hXzKeBF07Du8d4c',
    appId: '1:575931384947:ios:5dbcb172bef4d4ca615606',
    messagingSenderId: '575931384947',
    projectId: 'cardealer-187bf',
    storageBucket: 'cardealer-187bf.firebasestorage.app',
    iosBundleId: 'com.example.cardealer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbDl50mkTiDjFskxj1hXzKeBF07Du8d4c',
    appId: '1:575931384947:ios:5dbcb172bef4d4ca615606',
    messagingSenderId: '575931384947',
    projectId: 'cardealer-187bf',
    storageBucket: 'cardealer-187bf.firebasestorage.app',
    iosBundleId: 'com.example.cardealer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7CmbfmAWTPDxqZEvOWWxpPjLM_U2fKw',
    appId: '1:575931384947:web:9761dc9ad20f426e615606',
    messagingSenderId: '575931384947',
    projectId: 'cardealer-187bf',
    authDomain: 'cardealer-187bf.firebaseapp.com',
    storageBucket: 'cardealer-187bf.firebasestorage.app',
    measurementId: 'G-LS0ZJQFNSN',
  );
}
